# Overall information about the conference
name: Neuromatch Conference Box
current_edition: 2021-4
subtitle: A Demo Website for Neuromatch Conference (NMC), NMC Box
description: "Neuromatch Conference (NMC) held multiple virtual conferences during the COVID\
  \ pandemic. Each of our conferences has led the way in providing new innovations\
  \ to the virtual conference space. Many scientific conferences adopted our pipeline and\
  \ framework to their own conferences. However, to date, most organizers have to develop\
  \ their own tech stack for organizing the virtual conference. Here, we provide our framework\
  \ for organizing Neuromatch Conference, Neuromatch Conference (in a) Box.\
  \ We hope that other organizers, not limited to neuroscientists, can adapt our code\
  \ to create their own virtual conferences in the future.
"

# Find TZ name here
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# We use the TZ to parse information for each conference
main_timezone: America/New_York

# Theme can be selected between light or dark, and accent control color
theme: dark
accent: #9dcfe3

# Information for each conference edition
editions:
  - edition: 2020-1
    edition_name: "1.0"
    page_title: neuromatch 1.0
    registration_date:
      text: Anytime before March 30, 2020
      start: null
      end: March 30, 2020
    submission_date:
      text: March 25, 2020
      start: null
      end: March 25, 2020
    main_conference:
      text: March 30 - April 1, 2020
      start: March 30, 2020
      end: April 1, 2020
    event_time:
      start: "08:00"
      end: "20:00"
    twitter_hashtag: neuromatch2020
    tracks:
      - main
      - A
      - B
      - C
      - D
      - E
      - F
      - G
  - edition: 2020-2
    edition_name: "2.0"
    page_title: neuromatch 2.0
    registration_date:
      text: Anytime before May 20, 2020
      start: null
      end: May 20, 2020
    submission_date:
      text: April 20 to May 20, 2020
      start: April 20, 2020
      end: May 20, 2020
    main_conference:
      text: May 25 - 27, 2020
      start: May 25, 2020
      end: May 27, 2020
    event_time:
      start: "08:00"
      end: "20:00"
    twitter_hashtag: neuromatch2020
    tracks:
      - main
      - A
      - B
      - C
      - D
      - E
  - edition: 2020-3
    edition_name: "3.0"
    page_title: neuromatch 3.0
    registration_date:
      text: Anytime before October 30, 2020
      start: null
      end: October 30, 2020
    submission_date:
      text: October 7, 2020 | We welcome all abstracts in any topic area within neuroscience!
      start: null
      end: October 7, 2020
    main_conference:
      text: October 26 - 30, 2020
      start: October 26, 2020
      end: October 30, 2020
    event_time:
      start: "08:00"
      end: "20:00"
    twitter_hashtag: nmc3
    tracks:
      - stage
      - room 1
      - room 2
      - room 3
      - room 4
      - room 5
      - room 6
      - room 7
      - room 8
      - room 9
  - edition: 2021-4
    edition_name: "4.0"
    page_title: neuromatch box
    registration_date:
      text: Anytime since this is a demo website
      start: null
      end: null
    submission_date:
      text: Anytime, try submitting abstract below your profile
      start: null
      end: null
    main_conference:
      text: Put main conference text in config file
      start: null
      end: null
    event_time:
      start: "07:00"
      end: "21:00"
    twitter_hashtag: nmcbox
    tracks:
      - main
      - A
      - B
      - C
      - D
      - E

# Firebase collection for users and votes
firebase-collection:
  2020-1:
    users: "users"
    preferences: "preferences"
  2020-2:
    users: "users"
    preferences: "preferences"
  2020-3:
    users: "users"
    preferences: "preferences"
  2021-4:
    users: "users"
    preferences: "preferences"
