# Config related ingestion to ElasticSearch

# Elastic search
host: "localhost"
port: 9200
es_version: 7.4.0

# path to GRID CSV file and index name for GRID
# Download GRID from https://www.grid.ac/downloads
grid_version: 2021-06-15
grid_index: grid

# Path to file or Airtable ID to index submissions to ElasticSearch
# This example has 3 abstracts from CSV files and one on
editions:
  2021-4:
    airtable_id: "appcidVUHiMD8TU0s"
    table_name: "submissions"
    paper_index: agenda-2021-4

  2020-3:
    path: ../sitedata/agenda/agenda-2020-3.csv
    paper_index: agenda-2020-3

  2020-2:
    path: ../sitedata/agenda/agenda-2020-2.csv
    paper_index: agenda-2020-2

  2020-1:
    path: ../sitedata/agenda/agenda-2020-1.csv
    paper_index: agenda-2020-1
